server:
  port: 8082

spring:
  application:
    name: transaction-service


  data:
    mongodb:
      uri: mongodb+srv://hila31097:hila31097@cluster.0hmmqt4.mongodb.net/banking_transactions
#      //todo change to env variable
      auto-index-creation: true

  cache:
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=30m


logging:
  level:
    com.banking: DEBUG
    org.springframework.data.mongodb: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.banking.transactionservice.controller

app:
  cache:
    transaction-cache-name: transactions
  account-service:
    base-url: http://localhost:8081
    timeout: 5000

