server:
  port: 8082

spring:
  application:
    name: transaction-service

  config:
    import: optional:classpath:secrets.properties

  data:
    mongodb:
      uri: ${mongodb.uri}
      auto-index-creation: true

  cache:
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=30m

account-service:
  url: http://localhost:8081
  timeout: 5000

logging:
  level:
    com.banking: DEBUG
    org.springframework.data.mongodb: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.banking.transactionservice.controller




