server:
  port: 8082

spring:
  application:
    name: transaction-service

  config:
    import: optional:classpath:secrets.properties

  data:
    mongodb:
      uri: ${mongodb.uri}
      auto-index-creation: true

  cache:
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=30m

account-service:
  url: http://localhost:8081
  timeout: 5000

logging:
  level:
    com.banking: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cache: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId:-}] %logger{36} - %msg%n"
  file:
    name: logs/transaction-service.log
    max-size: 10MB
    max-history: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,caches,cache
  endpoint:
    health:
      show-details: always
    caches:
      enabled: true
    cache:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.banking.transactionservice.controller




