server:
  port: 8081

spring:
  application:
    name: account-service

  config:
    import: optional:classpath:secrets.properties

  data:
    mongodb:
      uri: ${mongodb.uri}
      auto-index-creation: true

  cache:
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=30m


logging:
  level:
    com.banking: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.banking.accountservice.controller

app:
  cache:
    account-cache-name: accounts
    customer-cache-name: customers